name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pack
        run: python3 generate.py classic low normal high

      - name: Zip Archive
        run: |
          for dir in /output/*/ do
            cd $dir &&
            dir=${dir%*/}
            7z a -mx9 -tzip ../../zip/kanoho-space-${dir##*/}.zip *
            && cd ../../
          done

      - name: Generate Hash
        run: python3 hash.py zip zip/checksums.txt

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zip/*
