name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest]
        preset: [classic, low, normal, high]

    steps:
      - uses: actions/checkout@v3

      - name: Generate
        run: python3 generate.py ${{ matrix.preset }}

      - name: Zip build
        run: 7z a -mx9 -tzip zip/kanoho-space-${{matrix.preset}}.zip output/*

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zip/*
          file_glob: true
          tag: ${{github.ref}}