name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pack
        run: python3 generate.py classic low normal high

      - name: Zip Archive
        run: cd output ; for i in *; do (cd $i ; 7z a -mx9 -tzip "../../zip/kanoho-space-$i.zip" *); done

      - name: Generate Checksum
        run: sha1sum zip/* > zip/checksums.zip

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zip/*
