name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Pack
        run: python3 generate.py classic low normal high

      - name: Install PackSquash
        run: |
          mkdir -p /etc/apt/keyrings && \
          sudo wget -O /etc/apt/keyrings/packsquash.key https://deb.packages.packsquash.aylas.org/public.key && \
          sudo echo 'deb [signed-by=/etc/apt/keyrings/packsquash.key] https://deb.packages.packsquash.aylas.org/debian stable main' > /etc/apt/sources.list.d/packsquash.list && \
          sudo apt update && \ 
          sudo apt install packsquash

      - name: Squash Packs
        working-directory: output
        run: for i in *; do (packsquash pack_directory=$i output_file_path="../../zip/kanoho-space-$i.zip" packsquash.toml); done

      - name: Generate Checksum
        working-directory: zip
        run: sha1sum * > checksums.txt

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zip/*
