name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Pack
        run: python3 generate.py classic low normal high

      - name: Install PackSquash
        run: |
          curl -Lo packsquash.zip https://github.com/ComunidadAylas/PackSquash/releases/download/v0.4.0/PackSquash.CLI.executable.x86_64-unknown-linux-musl.zip
          unzip packsquash.zip packsquash
          chmod +x packsquash

      - name: Squash Packs
        run: |
          mkdir ./zip
          for i in ./output/*; do
              PACK="$(basename "$i")"
              echo "Squishing pack preset: $PACK"
              CONFIG="$(sed -e "s/{PACK_DIRECTORY}/.\/output\/$PACK/" -e "s/{OUTPUT_FILE}/.\/zip\/kanoho-space-$PACK.zip/" "packsquash.toml")"
              printf "$CONFIG" | ./packsquash
          done

      - name: Generate Checksum
        working-directory: zip
        run: sha1sum * > checksums.txt

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zip/*
