name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: write

    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest]
        preset: [classic, low, normal, high]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pack
        run: python3 generate.py ${{ matrix.preset }}

      - name: Zip Archive
        run: cd output && 7z a -mx9 -tzip ../zip/kanoho-space-${{matrix.preset}}.zip *

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zip/*
